### ISSUE TITLE
Demo resetting database is too quick

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/demo.silverstripe.org#36] opened 2018-02-07 01:45 UTC
When using https://demo.silverstripe.org/admin changes are lost too quickly. I tested it several times and the database seems to reset every minute which means you can't really demo any of the editing features unless you are super quick (eg. adding pages/editing a page). This makes the CMS seem broken when it isn't. 

You get an error notification when trying to complete tasks on pages which are no longer existing but the error messages don't tell you anything meaningful to know what to do. 

There should also be a notification to say "The demo is resetting the database, all changes will be lost... this happens every Xmin..."

# PRs:

 - [ ] https://github.com/silverstripe/demo.silverstripe.org/pull/38

**Comment by clarkepaul** [comment] 2018-02-07 20:31
Cheers @robbieaverill, yeah I saw it was set to 20mins but still seems to refresh every minute (just confirmed the 1min again today).

**Comment by robbieaverill** [comment] 2018-02-07 20:42
Seems like it would be an SSP support ticket. What do you think @clarkepaul?

**Comment by clarkepaul** [comment] 2018-02-11 22:46
Yeah could be? or might even be the OS team. I've created a ticket for SSP and see what happens :)

**Comment by robbieaverill** [comment] 2018-02-26 02:17
Relevant info from SSP support:

The bug is occurring in this method:
https://github.com/silverstripe/silverstripe-crontask/blob/master/src/Controllers/CronTaskController.php#L67

When dumping out `$nextExpectedDate` it is set to `2017-04-26 09:20:00.000000` which seems to be because `$status->LastChecked` comes out as `2017-04-26 09:08:03`, therefore the next run is less than `$now` so the cron runs every minute.

Looking at the database this is confirmed:

```
mysql> select * FROM CronTaskStatus;
+----+--------------------------------------+---------------------+---------------------+-------------------------------+---------------------+---------+
| ID | ClassName                            | LastEdited          | Created             | TaskClass                     | LastChecked         | LastRun |
+----+--------------------------------------+---------------------+---------------------+-------------------------------+---------------------+---------+
|  1 | SilverStripe\CronTask\CronTaskStatus | 2017-04-26 09:08:03 | 2017-04-26 09:00:14 | GarbageCollectSessionCronTask | 2017-04-26 09:08:03 | NULL    |
|  2 | SilverStripe\CronTask\CronTaskStatus | 2017-04-26 09:08:03 | 2017-04-26 09:01:02 | DemoCronTask                  | 2017-04-26 09:08:03 | NULL    |
+----+--------------------------------------+---------------------+---------------------+-------------------------------+---------------------+---------+
2 rows in set (0.00 sec)
```

I'd recommend having a look in to why `LastChecked` isn't being updated in the ss4 demo for this task - perhaps because the database is constantly reset this is also?

**Comment by tractorcow** [comment] 2018-03-13 22:47
"last run date" for the cron task is stored in the DB.

The task itself resets the DB.

Seems pretty much an obvious logical error.

**Comment by tractorcow** [comment] 2018-03-13 23:21
Fixed with https://github.com/silverstripe/demo.silverstripe.org/pull/38

**Closed** 2018-03-14 00:01 UTC
Labels: bug
